version: '3.7'

services:

  database:

    image: postgres:12-alpine

    restart: always

    ports:

      - 5477:5432

    environment:

      POSTGRES_DB: nest

      POSTGRES_USER: docker

      POSTGRES_PASSWORD: docker